# Databricks notebook source
# MAGIC %md
# MAGIC # Step 12 — RAG System: Policy-Backed Claim Denial Explanations
# MAGIC
# MAGIC **Lineage:**
# MAGIC ```
# MAGIC workspace.gold.gold_claim_explanations ──► [ChromaDB RAG] ──► workspace.gold.gold_claim_policy_explanations
# MAGIC ```
# MAGIC
# MAGIC ## Architecture Decision Log
# MAGIC
# MAGIC | Decision | Choice | Reason |
# MAGIC |---|---|---|
# MAGIC | **Chunking** | Recursive Character Splitter | Policy docs have clear section headers (`SECTION 1`, `POLICY 1.1`). Recursive splitting on `\n\n → \n → . → space` keeps each rule semantically intact inside one chunk. |
# MAGIC | **Vector DB** | ChromaDB (EphemeralClient) | Runs 100% in-memory on Databricks CE driver RAM. Natively stores vectors + text + metadata together — no manual lookup dictionaries like FAISS. |
# MAGIC | **Embedding Model** | `all-MiniLM-L6-v2` | Open-source, no API key needed, downloads directly to Databricks cluster. 384-dim vectors, excellent semantic matching for policy text. |
# MAGIC | **Search Type** | Dense Vector Only | SHAP queries are rich sentences best matched semantically. BM25 keyword search recommended only in production if specific medical codes (e.g., `ICD-10-CM K50.012`) need exact matching. |
# MAGIC | **Input Masking** | Not Required | The RAG query is auto-generated from generic SHAP sentences (e.g., *"Diagnosis code is missing"*). No PII/PHI is ever sent to the vector database. |
# MAGIC | **Query Source** | Auto-Generated by Pipeline | The user never writes a RAG query. The pipeline converts `is_diag_missing=1` → SHAP value → `"The medical diagnosis code is missing"` → ChromaDB query. |
# MAGIC | **Top-K** | K=2 per SHAP reason | One query per SHAP reason (3 reasons per claim). K=2 ensures comprehensive coverage without irrelevant policy noise. |
# MAGIC | **LangGraph** | Not Used | This is a straight-through ETL batch job — no multi-turn agentic behaviour needed. |
# MAGIC | **Query Reformulation** | Not Required | SHAP reason sentences are already clean, declarative, and semantically aligned with policy language. |

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 1 — Install Dependencies
# MAGIC
# MAGIC **Important for Databricks CE:** Run this cell first and restart the Python kernel before proceeding.
# MAGIC Upload the 3 policy `.txt` files to `Data → DBFS → FileStore → policy_docs` before running Cell 3.

# COMMAND ----------

# DBTITLE 1,Cell 3
# MAGIC %pip install typing_extensions>=4.10.0 sentence-transformers chromadb

# COMMAND ----------

# DBTITLE 1,Restart Python
dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 2 — Imports & Config

# COMMAND ----------

# DBTITLE 1,Cell 6
import os
import re
import chromadb
import pandas as pd
import numpy as np
import warnings
from datetime import datetime
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

warnings.filterwarnings("ignore")

# ── Paths ─────────────────────────────────────────────────────────────────────
# Policy documents are stored in Unity Catalog Volumes
POLICY_DOCS_PATH = "/Volumes/workspace/rag_policy_docs/policy_docs"

# ── ChromaDB & Embedding ───────────────────────────────────────────────────────
EMBED_MODEL  = "all-MiniLM-L6-v2"
COLLECTION   = "insurance_policies"
TOP_K        = 2   # Retrieve top-2 policy chunks per SHAP reason query

# ── Chunking Parameters ────────────────────────────────────────────────────────
MAX_WORDS    = 180  # ~180 words keeps one policy rule intact per chunk
OVERLAP_WORDS = 25  # 25-word overlap avoids losing context at chunk boundaries

# ── Tables ────────────────────────────────────────────────────────────────────
INPUT_TABLE  = "workspace.gold.gold_claim_explanations"
OUTPUT_TABLE = "workspace.gold.gold_claim_policy_explanations"

print("=" * 60)
print("RAG PIPELINE — CONFIG")
print("=" * 60)
print(f"Vector DB        : ChromaDB (EphemeralClient — in-memory)")
print(f"Embedding model  : {EMBED_MODEL}")
print(f"Top-K per reason : {TOP_K}")
print(f"Chunk size       : {MAX_WORDS} words  |  Overlap: {OVERLAP_WORDS} words")
print(f"Input table      : {INPUT_TABLE}")
print(f"Output table     : {OUTPUT_TABLE}")
print(f"Policy docs path : {POLICY_DOCS_PATH}")
print("=" * 60)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 3 — Recursive Character Text Splitter
# MAGIC
# MAGIC **Why Recursive?** Our policy documents have a clear hierarchy:
# MAGIC - `SECTION 1` → `POLICY 1.1` → paragraph → sentence → word
# MAGIC
# MAGIC The recursive splitter respects this by trying separators in order:
# MAGIC `\n\n` (section break) → `\n` (line break) → `. ` (sentence) → ` ` (word)
# MAGIC
# MAGIC This guarantees that `POLICY 1.1 — Maximum Billable Amount...` stays in one chunk
# MAGIC instead of being cut mid-sentence by a fixed-size splitter.

# COMMAND ----------

def recursive_char_split(text: str, max_words: int, overlap: int) -> list:
    """
    Recursively splits text into chunks by trying structural separators in order.
    Each chunk tries to stay within `max_words`, with `overlap` words shared
    between consecutive chunks to avoid losing boundary context.
    
    Separator priority (most structural → least structural):
      1. \\n\\n  — section/paragraph break
      2. \\n    — line break
      3. '. '   — sentence boundary
      4. ' '    — word boundary (final fallback)
    """
    SEPARATORS = ["\n\n", "\n", ". ", " "]

    def _split(segment: str, sep_index: int) -> list:
        # Base case: if no more structural separators, split by raw word count
        if sep_index >= len(SEPARATORS):
            words = segment.split()
            result = []
            i = 0
            while i < len(words):
                result.append(" ".join(words[i : i + max_words]))
                i += max_words - overlap
            return result

        sep = SEPARATORS[sep_index]
        parts = [p.strip() for p in segment.split(sep) if p.strip()]

        # Merge parts greedily until a chunk would exceed max_words
        chunks = []
        buffer = ""
        for part in parts:
            candidate = (buffer + " " + part).strip() if buffer else part
            if len(candidate.split()) <= max_words:
                buffer = candidate
            else:
                if buffer:
                    chunks.append(buffer)
                    # Carry overlap forward into next chunk
                    overlap_text = " ".join(buffer.split()[-overlap:]) if overlap else ""
                    buffer = (overlap_text + " " + part).strip()
                else:
                    # Part alone is too large — recurse deeper with next separator
                    sub = _split(part, sep_index + 1)
                    chunks.extend(sub)
                    buffer = ""
        if buffer:
            chunks.append(buffer)
        return chunks

    # Normalise whitespace before splitting
    text = re.sub(r" {2,}", " ", text.strip())
    return _split(text, 0)


def load_and_chunk_documents(docs_path: str, max_words: int, overlap: int) -> list:
    """
    Loads all .txt files from docs_path, applies recursive character splitting,
    and returns a flat list of chunk dicts: {chunk_id, source_doc, text}.
    """
    policy_files = sorted([f for f in os.listdir(docs_path) if f.endswith(".txt")])
    if not policy_files:
        raise FileNotFoundError(f"No .txt files found at: {docs_path}")

    all_chunks = []
    for filename in policy_files:
        with open(os.path.join(docs_path, filename), "r", encoding="utf-8") as fh:
            raw_text = fh.read()

        chunks = recursive_char_split(raw_text, max_words, overlap)
        for i, chunk_text in enumerate(chunks):
            all_chunks.append({
                "chunk_id"  : f"{filename}__chunk_{i}",
                "source_doc": filename,
                "text"      : chunk_text,
            })
        print(f"  [{filename}] → {len(chunks)} chunks")

    print(f"\nTotal chunks across all 3 policy documents: {len(all_chunks)}")
    return all_chunks


print("Loading and chunking policy documents...")
all_chunks = load_and_chunk_documents(POLICY_DOCS_PATH, MAX_WORDS, OVERLAP_WORDS)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 4 — Initialise ChromaDB & Index Policy Chunks
# MAGIC
# MAGIC ChromaDB stores **vectors + document text + metadata** natively.
# MAGIC The `SentenceTransformerEmbeddingFunction` handles embedding automatically —
# MAGIC no manual `.encode()` calls needed. ChromaDB embeds both documents (at index time)
# MAGIC and queries (at retrieval time) using the same model, ensuring consistent vector space.

# COMMAND ----------

# Initialise in-memory ChromaDB client (Databricks CE compatible — no external server)
chroma_client = chromadb.EphemeralClient()

# Sentence Transformer embedding function (all-MiniLM-L6-v2, no API key)
embedding_fn = SentenceTransformerEmbeddingFunction(model_name=EMBED_MODEL)

# Create collection with cosine similarity metric
# Delete if already exists (handles re-runs in the same session)
try:
    chroma_client.delete_collection(COLLECTION)
except Exception:
    pass

collection = chroma_client.create_collection(
    name     = COLLECTION,
    embedding_function = embedding_fn,
    metadata = {"hnsw:space": "cosine"},  # cosine similarity for semantic matching
)

# Index all chunks — ChromaDB generates embeddings internally
collection.add(
    documents = [c["text"]       for c in all_chunks],
    metadatas = [{"source_doc": c["source_doc"], "chunk_id": c["chunk_id"]} for c in all_chunks],
    ids       = [c["chunk_id"]   for c in all_chunks],
)

print(f"✅ ChromaDB collection '{COLLECTION}' built.")
print(f"   Total indexed chunks : {collection.count()}")
print(f"   Embedding model      : {EMBED_MODEL}")
print(f"   Similarity metric    : Cosine")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 5 — Load `gold_claim_explanations` (SHAP Outputs)

# COMMAND ----------

explanations_spark = spark.table(INPUT_TABLE)
explanations_pd    = explanations_spark.toPandas()

print(f"Loaded {INPUT_TABLE}: {len(explanations_pd):,} rows")
print(f"  Denied claims   : {(explanations_pd['predicted_status']=='DENIED').sum():,}")
print(f"  Approved claims : {(explanations_pd['predicted_status']=='APPROVED').sum():,}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 6 — ChromaDB Query Function
# MAGIC
# MAGIC **Automated Query Flow (no user input required):**
# MAGIC
# MAGIC ```
# MAGIC Raw Claim Data (structured)
# MAGIC     ↓
# MAGIC ML Model → SHAP Values → Reason Mapper
# MAGIC     ↓
# MAGIC "The medical diagnosis code is missing or invalid."   ← AUTO-GENERATED QUERY
# MAGIC     ↓
# MAGIC ChromaDB (cosine similarity search)
# MAGIC     ↓
# MAGIC "POLICY 2.1 — All claims MUST contain a valid ICD-10-CM diagnosis code..."
# MAGIC ```
# MAGIC
# MAGIC One query is issued **per SHAP reason** (3 queries per denied claim).
# MAGIC Each query retrieves K=2 policy chunks, ensuring every reason
# MAGIC gets its own directly relevant supporting policy text.

# COMMAND ----------

def query_policy(reason_text: str, top_k: int = TOP_K) -> list:
    """
    Queries ChromaDB with a SHAP-generated denial reason sentence.
    Returns top_k most semantically similar policy chunks.
    
    The query IS the SHAP reason sentence — fully auto-generated by the
    pipeline. No user writes this text manually.
    
    Returns:
        List of dicts: [{policy_text, source_doc, similarity_score}, ...]
    """
    if not reason_text or reason_text.strip() == "":
        return []

    results = collection.query(
        query_texts = [reason_text],
        n_results   = top_k,
        include     = ["documents", "metadatas", "distances"],
    )

    output = []
    for doc, meta, dist in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0],
    ):
        # ChromaDB cosine distance → similarity score (0=identical, 2=opposite)
        # Convert: similarity = 1 - (distance / 2) to get a 0–1 score
        similarity = round(1 - dist / 2, 4)
        output.append({
            "policy_text"     : doc,
            "source_doc"      : meta.get("source_doc", "unknown"),
            "similarity_score": similarity,
        })
    return output


# Quick sanity-check query
_test = query_policy("The medical procedure code is missing or invalid.")
print("Query test: 'The medical procedure code is missing or invalid.'")
print(f"  Top result source : {_test[0]['source_doc']}")
print(f"  Similarity score  : {_test[0]['similarity_score']}")
print(f"  Policy snippet    : {_test[0]['policy_text'][:120]}...")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 7 — Build Combined Explanation Rows
# MAGIC
# MAGIC **For each DENIED claim:**
# MAGIC - Reason 1 text → ChromaDB query → Best matching policy passage
# MAGIC - Reason 2 text → ChromaDB query → Best matching policy passage
# MAGIC - Reason 3 text → ChromaDB query → Best matching policy passage
# MAGIC - All assembled into a clean `full_explanation` string
# MAGIC
# MAGIC **For APPROVED claims:** No policy retrieval. Policy columns set to "N/A — Claim Approved."

# COMMAND ----------

PROCESSED_AT = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
output_rows  = []

print(f"Processing {len(explanations_pd):,} claims through RAG pipeline...")

for _, row in explanations_pd.iterrows():

    base = {
        "claim_id"          : row["claim_id"],
        "predicted_status"  : row["predicted_status"],
        "denial_probability": row["denial_probability"],
        "processed_at"      : PROCESSED_AT,
    }

    if row["predicted_status"] == "DENIED":

        reason_texts = [
            str(row.get("reason_1_text", "")),
            str(row.get("reason_2_text", "")),
            str(row.get("reason_3_text", "")),
        ]

        # Query ChromaDB independently for each of the 3 SHAP reasons
        policy_hits = []
        for r_text in reason_texts:
            hits = query_policy(r_text, top_k=1)  # Best policy per reason
            policy_hits.append(hits[0] if hits else {
                "policy_text": "No matching policy found.",
                "source_doc" : "N/A",
                "similarity_score": 0.0,
            })

        # Populate structured columns
        for i in range(3):
            base[f"reason_{i+1}_text"]          = reason_texts[i]
            base[f"policy_{i+1}_text"]          = policy_hits[i]["policy_text"]
            base[f"policy_{i+1}_source"]        = policy_hits[i]["source_doc"]
            base[f"policy_{i+1}_similarity"]    = policy_hits[i]["similarity_score"]

        # Build the human-readable full explanation (matches the agreed response format)
        explanation_lines = [
            f"CLAIM ID: {row['claim_id']}",
            f"STATUS  : DENIED  (Denial Probability: {row['denial_probability']*100:.1f}%)",
            "",
        ]
        for i in range(3):
            explanation_lines += [
                f"REASON {i+1} (From ML Model + SHAP):",
                f"  {reason_texts[i]}",
                f"SUPPORTING POLICY (Source: {policy_hits[i]['source_doc']}):",
                f"  \"{policy_hits[i]['policy_text'][:350]}...\"",
                "",
            ]
        base["full_explanation"] = "\n".join(explanation_lines)

    else:  # APPROVED
        for i in range(3):
            base[f"reason_{i+1}_text"]       = row.get(f"reason_{i+1}_text", "N/A")
            base[f"policy_{i+1}_text"]       = "N/A — Claim meets all adjudication standards."
            base[f"policy_{i+1}_source"]     = "N/A"
            base[f"policy_{i+1}_similarity"] = 0.0

        base["full_explanation"] = (
            f"CLAIM ID: {row['claim_id']}\n"
            f"STATUS  : APPROVED  (Denial Probability: {row['denial_probability']*100:.1f}%)\n"
            f"No policy violations detected. Claim meets all adjudication standards."
        )

    output_rows.append(base)


output_pd = pd.DataFrame(output_rows)

# Enforce column order
col_order = [
    "claim_id", "predicted_status", "denial_probability",
    "reason_1_text", "policy_1_text", "policy_1_source", "policy_1_similarity",
    "reason_2_text", "policy_2_text", "policy_2_source", "policy_2_similarity",
    "reason_3_text", "policy_3_text", "policy_3_source", "policy_3_similarity",
    "full_explanation", "processed_at",
]
output_pd = output_pd[col_order]

print(f"\n✅ Combined explanation table built: {len(output_pd):,} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 8 — Write `gold_claim_policy_explanations` to Gold Layer

# COMMAND ----------

output_spark = spark.createDataFrame(output_pd)

print("Schema of gold_claim_policy_explanations:")
output_spark.printSchema()

(
    output_spark
    .write
    .format("delta")
    .mode("overwrite")
    .saveAsTable(OUTPUT_TABLE)
)

print(f"\n✅ Table written: {OUTPUT_TABLE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 9 — Verify: Read Back & Spot-Check Full Explanations

# COMMAND ----------

verify_df = spark.table(OUTPUT_TABLE)

print("=" * 65)
print(f"VERIFICATION: {OUTPUT_TABLE}")
print("=" * 65)
print(f"Row count : {verify_df.count():,}\n")

# Print the top 3 most confidently DENIED claims with full explanation
top_denied = (
    output_pd[output_pd["predicted_status"] == "DENIED"]
    .sort_values("denial_probability", ascending=False)
    .head(3)
)

print("--- TOP 3 MOST CONFIDENTLY DENIED CLAIMS ---\n")
for _, r in top_denied.iterrows():
    print("=" * 70)
    print(r["full_explanation"])
    print("=" * 70)
    print()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 10 — RAG Quality Check: Policy Retrieval Analysis

# COMMAND ----------

denied_pd = output_pd[output_pd["predicted_status"] == "DENIED"].copy()

# Which policy document is retrieved most often as the primary support
src_counts = denied_pd["policy_1_source"].value_counts().reset_index()
src_counts.columns = ["policy_document", "times_as_primary"]
src_counts["pct"]  = (src_counts["times_as_primary"] / len(denied_pd) * 100).round(1)

print("=" * 65)
print("RAG QUALITY CHECK — Primary Policy Source Distribution")
print("=" * 65)
print(src_counts.to_string(index=False))

# Average similarity scores per reason slot
for slot in [1, 2, 3]:
    col = f"policy_{slot}_similarity"
    avg = denied_pd[col].mean()
    status = "✅ Good" if avg > 0.50 else "⚠️ Review"
    print(f"\nAvg similarity — Reason {slot} queries: {avg:.4f}  {status}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cell 11 — Pipeline Summary

# COMMAND ----------

print("=" * 65)
print("  WEEK 5 + 6 — XAI + RAG PIPELINE SUMMARY")
print("=" * 65)
print(f"  Input  : {INPUT_TABLE}")
print(f"  Output : {OUTPUT_TABLE}")
print(f"  Rows   : {len(output_pd):,}  ({(output_pd['predicted_status']=='DENIED').sum()} DENIED / {(output_pd['predicted_status']=='APPROVED').sum()} APPROVED)")
print()
print("  XAI Layer :")
print(f"    Method        : SHAP TreeExplainer (exact Shapley values)")
print(f"    Top-N reasons : 3 per claim")
print()
print("  RAG Layer :")
print(f"    Vector DB     : ChromaDB EphemeralClient (in-memory, CE compatible)")
print(f"    Embedding     : {EMBED_MODEL} (384-dim, no API key)")
print(f"    Chunking      : Recursive Character Splitter (section-aware)")
print(f"    Chunks indexed: {collection.count()}")
print(f"    Query source  : Auto-generated from SHAP reason text (no user query)")
print(f"    Top-K         : {TOP_K} policy chunks per reason query")
print()
print("  Output columns per claim:")
print("    claim_id                  — Primary key")
print("    predicted_status          — DENIED / APPROVED")
print("    denial_probability        — Model's confidence")
print("    reason_1/2/3_text         — SHAP-derived business explanation")
print("    policy_1/2/3_text         — Matched policy passage from ChromaDB")
print("    policy_1/2/3_source       — Policy document filename")
print("    policy_1/2/3_similarity   — Cosine similarity score (0–1)")
print("    full_explanation          — Complete human-readable denial letter")
print("    processed_at              — UTC timestamp")
print("=" * 65)
